language: android

android:
  components:
    # - tools
    # - platform-tools
    # - extra
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    #- extra-android-support
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

branches:
  only:
    - develop

before_script:
    - chmod +x gradlew
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "travis.job=$TRAVIS_JOB_NUMBER" >> local.properties
    - mkdir app/signingConfigs
    - echo 'signingConfigs{ release {} }' > app/signingConfigs/release.gradle
    - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc

script:
    - ./gradlew assembleDebug --stacktrace --info

after_success:
  - ./gradlew crashlyticsUploadDistributionDebug

