language: android

sudo: false

env:
  global:
    - JAVA_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
    - MALLOC_ARENA_MAX=2
    - secure: "d3vnsXF2Yp5oIOTJ0jLecMTuC2wRvRivN4wJhz5VL6OcUjlE253MM5+cdOgoAm3zRDVX0MWY67lP8Ftz9moZe4kqHitN9CvGIdelTMa67TYePCvkBjUjfEL9h8HgO/d0yN8Z9DNKYt9wlFJ2PWk63CLKTcOulX0tYLdJNUiNcDn5TZtTQ9AhBru5sji9WZmTX0y0GDOml352r3ZBmwFDeJeNQKUQdtAKPe9eqEZ+4kfJ0RDrRUTotx0871LOUr4S8GD8U/SzahL26Zwu+U72KC+3Dq+fLUzD/3khI2wQzZms/4qzQ15IL7FF9Bw/WbX5xtEkL9Sx3k0FZVfQLKfjIE670Z2DsGAlzvJiO2H+OJdvbETo+WvMj6nIfAWI8B5Mg7ynq4bR14HMwbfFM4IkMOEhoHGytnubGQVtbmZtmfO332tCXT6Pu9Gy3XrfexEubcjqzcW0UtEcLR8DAOPflfqhSUGEmGVkBJv0JJMPqomY1M03g4qf9NLPxKgv8XcPHG5GggXzAfQ8MPXnd2upbEdACoEm9n7GpICgsENyHaMYJO7agavY15Z2w2XC29zX+fSs2WACN4Arh6TJqk3K1nOytMb4hBWj3yEqxuGGSCmWu0P0Dpz3E1Slrf/pVDUMWXi2STF0y0HA2O6GIiVhbBmeASPoy4Ij8rwKdMhQtYU="

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

branches:
  only:
    - develop

before_script:
    - chmod +x gradlew
    - chmod +x deploy_beta.sh
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "travis.job=$TRAVIS_JOB_NUMBER" >> local.properties
    - mkdir app/signingConfigs
    - echo 'signingConfigs{ release {} }' > app/signingConfigs/release.gradle
    - echo "apiSecret=$FABRIC_API_SECRET" > app/fabric.properties
    # see https://github.com/travis-ci/travis-ci/issues/2496
    - ulimit -t 514029
    # Emulator
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./gradlew assembleProductionDebug assembleProductionDebugAndroidTest -PdisablePreDex --stacktrace --info

after_success:
  - ./deploy_beta.sh
