language: android

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk8

branches:
  only:
    - develop

before_script:
    - chmod +x gradlew
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "travis.job=$TRAVIS_JOB_NUMBER" >> local.properties

script:
    - ./gradlew clean assembleDebug

after_success:
  - ./gradlew crashlyticsUploadDistributionDebug

