language: android

sudo: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_script:
    - chmod +x gradlew
    - chmod +x main.sh
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "travis.job=$TRAVIS_JOB_NUMBER" >> local.properties
    - mkdir app/signingConfigs
    - echo 'signingConfigs{ release {} }' > app/signingConfigs/release.gradle
    # see https://github.com/travis-ci/travis-ci/issues/2496
    - ulimit -t 514029
    # Emulator
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - ./main.sh

after_success:
