language: android

sudo: required

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

branches:
  only:
    - develop

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

before_script:
    - chmod +x gradlew
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "travis.job=$TRAVIS_JOB_NUMBER" >> local.properties
    - mkdir app/signingConfigs
    - echo 'signingConfigs{ release {} }' > app/signingConfigs/release.gradle
    - echo "apiSecret=$FABRIC_API_SECRET" > app/fabric.properties

script:
    - ./gradlew clean assembleDebug -PdisablePreDex --stacktrace --info

after_success:
  - ./gradlew crashlyticsUploadDistributionDebug -PdisablePreDex --stacktrace --info

