name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: dummy
      run: |
        echo appId=ca-app-pub-3940256099942544~3347511713 > ads.properties
        echo unitId=ca-app-pub-3940256099942544/6300978111touch >> ads.properties
    - name: ktlint
      run: ./gradlew ktlintCheck
    - name: Generate kover coverage report
      run: ./gradlew koverXmlReportDebug
    - name: Add coverage report to PR
      id: kover
      uses: mi-kas/kover-report@v1
      with:
        path: |
          ${{ github.workspace }}/app/build/reports/kover/reportDebug.xml
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 80
        min-coverage-changed-files: 80
        coverage-counter-type: LINE
    - name: Check coverage for changed files
      id: check-coverage
      run: |
        if [ "${{ steps.kover.outputs.coverage-changed-files }}" -ne 100 ]; then
          echo "Coverage for changed files is less than 100%."
          exit 1
        fi
    - name: Coverage Check Passed
      if: success()
      run: echo "Coverage is sufficient for merging."
